### PR TITLE
Add production config

### PR DESCRIPTION
**Pull request by TheNeikos**

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 3640dc57a64c192f15779d1be84ef617d179851e
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 10e62a12a1bd362547c80273d7e2f7f5bf0a68d9
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

See here for a few examples: [Convention](https://github.com/ajoslin/conventional-changelog/blob/a5505865ff3dd710cf757f50530e73ef0ca641da/conventions/angular.md)

---
This message was auto-generated by https://gitcop.com

**Comment by TheNeikos** [comment]
@homu r+

**Comment by TheNeikos** [comment]
@homu r-

**Comment by TheNeikos** [comment]
@homu r+

**Pull request merged**
